CREATE TABLE IDENTIFYCHIPS(
   IDCARD NVARCHAR(20) PRIMARY KEY     NOT NULL,
   NAME           NVARCHAR(30)    NOT NULL,
   ISSUE            INT     NOT NULL,
   PHONE           NVARCHAR(15) NOT NULL,
   ADDRESS        NVARCHAR(100)
);

CREATE TABLE USERS(
   NAME           TEXT    NOT NULL,
   PASSWORD        NVARCHAR(20) NOT NULL,
   ROLE            int
);

INSERT INTO IDENTIFYCHIPS (IDCARD, NAME, ISSUE, HOUSE, ADDRESS) VALUES ('350425199103222619', '周天', 1, 'A#701', '福州市晋安区');
INSERT INTO IDENTIFYCHIPS (IDCARD, NAME, ISSUE, HOUSE, ADDRESS) VALUES ('350425199002804619', '周一', 1, 'A#702', '福州市鼓楼区');

INSERT INTO USERS (NAME, PASSWORD, ROLE) VALUES ('admin', '123', 0);

SELECT * from IDENTIFYCHIPS